### ISSUE TITLE
1 - HTML structure

### ISSUE THREAD

**Issue by dinozio-design** [dinozio-design/CRM-lite#8]
- [x] use the initiated index.html (home page) file and create the structure and elements based on the wireframe
- [x] use the initiated addNewApointment.html file and create the structure and elements based on the wireframe
- [x] make the static HTML page
- [x] make the page look like the wireframe

**Comment by VithusanU** [comment]
1) Have made the index.html (basic page W buttons and css styling)
2)  Have made the addNewAppointment.html (basic page W buttons and css styling)
